### ISSUE TITLE
CPU Error 

### ISSUE THREAD

**Issue by impulsecorp** [titu1994/progressive-neural-architecture-search#4]
Your program works fine for me on an AWS Ubuntu 16.04 GPU server, but when I switch the exact same AWS hard drive image to a CPU server, this error happens after the end of the first round of 36 testing, when the RNN controller surrogate network starts.

Model #36 / #36
Predicted actions :  [0, '3x3 avgpool', 0, '3x3 avgpool']
Train on 1000 samples, validate on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 0s 335us/step - loss: 11.4135 - acc: 0.1030 - val_loss: 10.0921 - val_acc: 0.0990

Epoch 00001: val_acc improved from -inf to 0.09900, saving model to weights/temp_network.h5
Epoch 2/5
1000/1000 [==============================] - 0s 194us/step - loss: 10.0787 - acc: 0.0940 - val_loss: 10.0075 - val_acc: 0.0930

Epoch 00002: val_acc did not improve from 0.09900
Epoch 3/5
1000/1000 [==============================] - 0s 195us/step - loss: 9.1449 - acc: 0.0980 - val_loss: 8.5515 - val_acc: 0.0930

Epoch 00003: val_acc did not improve from 0.09900
Epoch 4/5
1000/1000 [==============================] - 0s 197us/step - loss: 7.7319 - acc: 0.0890 - val_loss: 7.5199 - val_acc: 0.0970

Epoch 00004: val_acc did not improve from 0.09900
Epoch 5/5
1000/1000 [==============================] - 0s 197us/step - loss: 7.5267 - acc: 0.0950 - val_loss: 7.5087 - val_acc: 0.1200

Epoch 00005: val_acc improved from 0.09900 to 0.12000, saving model to weights/temp_network.h5
1000/1000 [==============================] - 0s 68us/step

Manager: Accuracy =  0.12000000238418579
Final Accuracy :  0.12000000238418579

Finished 36 out of 36 models !

Controller: Number of training steps required for this stage : 360

Controller: Begin training epoch 1

Controller: Begin training - B = 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,21] = 6 is not in [0, 6)
         [[Node: controller/policy_network/embedding/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@losse.../AssignSub"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](policy_network/state_embeddings/read, _arg_controller/policy_network/state_input/state_input_0_0, controller/policy_network/embedding/embedding_lookup/axis)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 111, in <module>
    loss = controller.train_step(rewards)
  File "/home/ubuntu/pnas/encoder.py", line 521, in train_step
    feed_dict=feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,21] = 6 is not in [0, 6)
         [[Node: controller/policy_network/embedding/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@losse.../AssignSub"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](policy_network/state_embeddings/read, _arg_controller/policy_network/state_input/state_input_0_0, controller/policy_network/embedding/embedding_lookup/axis)]]

Caused by op 'controller/policy_network/embedding/embedding_lookup', defined at:
  File "train.py", line 69, in <module>
    restore_controller=RESTORE_CONTROLLER)
  File "/home/ubuntu/pnas/encoder.py", line 357, in __init__
    self.build_policy_network()
  File "/home/ubuntu/pnas/encoder.py", line 401, in build_policy_network
    embeddings = tf.nn.embedding_lookup(embedding_weights, state_input)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/embedding_ops.py", line 308, in embedding_lookup
    transform_fn=None)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/embedding_ops.py", line 131, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 2666, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3141, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[0,21] = 6 is not in [0, 6)
         [[Node: controller/policy_network/embedding/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@losse.../AssignSub"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](policy_network/state_embeddings/read, _arg_controller/policy_network/state_input/state_input_0_0, controller/policy_network/embedding/embedding_lookup/axis)]]

ubuntu@ip-172-31-43-172:~/pnas$

**Comment by titu1994** [comment]
The codebase has been updated to use tf.keras and Eager execution (the default in TF 2.0). Its a lot more stable than before in the few tests I've done.
