### ISSUE TITLE
InvalidArgumentError 

### ISSUE THREAD

**Issue by glard** [titu1994/progressive-neural-architecture-search#6]
Every time I ran the program, this error showed up, Can you help me about it?

Manager: Accuracy =  0.1414
Final Accuracy :  0.1414

Finished 36 out of 36 models ! 

Controller: Number of training steps required for this stage : 360

Controller: Begin training epoch 1

Controller: Begin training - B = 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,21] = 6 is not in [0, 6)
	 [[Node: controller/policy_network/embedding/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@losse.../AssignSub"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](policy_network/state_embeddings/read, _arg_controller/policy_network/state_input/state_input_0_0, controller/policy_network/embedding/embedding_lookup/axis)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/85/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/rick/progressive-neural-architecture-search/progressive-neural-architecture-search/train.py", line 95, in <module>
    loss = controller.train_step(rewards)
  File "/home/rick/progressive-neural-architecture-search/progressive-neural-architecture-search/encoder.py", line 521, in train_step
    feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,21] = 6 is not in [0, 6)
	 [[Node: controller/policy_network/embedding/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@losse.../AssignSub"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](policy_network/state_embeddings/read, _arg_controller/policy_network/state_input/state_input_0_0, controller/policy_network/embedding/embedding_lookup/axis)]]

Caused by op 'controller/policy_network/embedding/embedding_lookup', defined at:
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/85/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/rick/progressive-neural-architecture-search/progressive-neural-architecture-search/train.py", line 53, in <module>
    restore_controller=RESTORE_CONTROLLER)
  File "/home/rick/progressive-neural-architecture-search/progressive-neural-architecture-search/encoder.py", line 357, in __init__
    self.build_policy_network()
  File "/home/rick/progressive-neural-architecture-search/progressive-neural-architecture-search/encoder.py", line 401, in build_policy_network
    embeddings = tf.nn.embedding_lookup(embedding_weights, state_input)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/embedding_ops.py", line 308, in embedding_lookup
    transform_fn=None)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/embedding_ops.py", line 131, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 2666, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3141, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[0,21] = 6 is not in [0, 6)
	 [[Node: controller/policy_network/embedding/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@losse.../AssignSub"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](policy_network/state_embeddings/read, _arg_controller/policy_network/state_input/state_input_0_0, controller/policy_network/embedding/embedding_lookup/axis)]]

**Comment by titu1994** [comment]
Interesting. Its trying to use the older way of embeddings, which took as input direct one hot encodings. The current version uses an embedding layer to project each id into a continuous domain.

Have you tried downloading the whole github repo again and trying ?

**Comment by glard** [comment]
I have already used the latest version. However, this error keeps coming out after finishing calculating the models.

**Comment by titu1994** [comment]
The codebase has been updated to use tf.keras and Eager execution (the default in TF 2.0). Its a lot more stable than before in the few tests I've done.
