### ISSUE TITLE
AttributeError:'module'object has no attribute 'initializers'

### ISSUE THREAD

**Issue by fanzhaowei** [titu1994/progressive-neural-architecture-search#7]
@titu1994 I am sorry to bother you!When I run python train.py,I got the error AttributeError:'module'object has no attribute 'initializers',Do you know how to solve it ? thank you!

**Comment by titu1994** [comment]
Can you print the entire stack trace ? I don't specifically import Keras initializers anywhere. 

Perhaps it's due to outdated Keras version ?

**Comment by fanzhaowei** [comment]
Keras                              2.1.2                     
Keras-Applications                 1.0.6                     
Keras-Preprocessing                1.0.5

**Comment by fanzhaowei** [comment]
Keras                              2.1.2                     
Keras-Applications                 1.0.6                     
Keras-Preprocessing                1.0.5   
@titu1994 thanks!

**Comment by fanzhaowei** [comment]
b306@cv:~/fanzhaowei/progressive-neural-architecture-search-master$ python train.py
Using TensorFlow backend.
2018-11-27 16:25:03.426953: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-27 16:25:03.427022: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-27 16:25:03.427042: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-11-27 16:25:03.699710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
2018-11-27 16:25:03.820312: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x2ba0eb0 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2018-11-27 16:25:03.820915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 1 with properties:
name: GeForce GT 710
major: 3 minor: 5 memoryClockRate (GHz) 0.954
pciBusID 0000:01:00.0
Total memory: 979.56MiB
Free memory: 836.81MiB
2018-11-27 16:25:03.820982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 0 and 1
2018-11-27 16:25:03.821006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 1 and 0
2018-11-27 16:25:03.821029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1
2018-11-27 16:25:03.821051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0: Y N
2018-11-27 16:25:03.821066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1: N Y
2018-11-27 16:25:03.821094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
2018-11-27 16:25:03.821119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1017] Ignoring gpu device (device: 1, name: GeForce GT 710, pci bus id: 0000:01:00.0) with Cuda multiprocessor count: 1. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
()
Obtaining search space for b = 1
('Search space size : ', 36)
('', 'STATE SPACE', '')
{ 'id': 0,
'index_map_': { 0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
'name': 'inputs',
'size': 5,
'value_map_': { 0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
'values': [0, 1, 2, 3, 4]}
()
{ 'id': 1,
'index_map_': { 0: '3x3 dconv',
1: '5x5 dconv',
2: '7x7 dconv',
3: '1x7-7x1 conv',
4: '3x3 maxpool',
5: '3x3 avgpool'},
'name': 'ops',
'size': 6,
'value_map_': { '1x7-7x1 conv': 3,
'3x3 avgpool': 5,
'3x3 dconv': 0,
'3x3 maxpool': 4,
'5x5 dconv': 1,
'7x7 dconv': 2},
'values': ['3x3 dconv', '5x5 dconv', '7x7 dconv', '1x7-7x1 conv', '3x3 maxpool', '3x3 avgpool']}
()
('Total number of models : ', 292)
()
Traceback (most recent call last):
File "train.py", line 53, in 
restore_controller=RESTORE_CONTROLLER)
File "/home/b306/fanzhaowei/progressive-neural-architecture-search-master/encoder.py", line 357, in init
self.build_policy_network()
File "/home/b306/fanzhaowei/progressive-neural-architecture-search-master/encoder.py", line 400, in build_policy_network
initializer = tf.initializers.random_uniform(-1., 1.))
AttributeError: 'module' object has no attribute 'initializers
@titu1994

**Comment by titu1994** [comment]
The codebase has been updated to use tf.keras and Eager execution (the default in TF 2.0). Its a lot more stable than before in the few tests I've done.
